# Generated by Django 5.2 on 2025-07-13 15:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MoodEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mood",
                    models.CharField(
                        choices=[
                            ("Happy", "Happy"),
                            ("Sad", "Sad"),
                            ("Angry", "Angry"),
                            ("Relaxed", "Relaxed"),
                            ("Excited", "Excited"),
                        ],
                        max_length=20,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("date", models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
